default: &default
  adapter: postgresql
  host: localhost
  username: kaya_active-rw
  password: kaya_active

development:
  <<: *default
  database: kaya_active_development

test:
  <<: *default
  database: kaya_active_test

